# Workflow name that appears in the GitHub Actions UI
name: Post welcome comment

# specifies a trigger for when the workflow should run
on:
  pull_request:
    types: [opened]  # Trigger on when a new pull request is opened
permissions:
  pull-requests: write  # set permissions for the workflow write comments on a pull request

# associated with a runner
jobs:
  build:
    name: Post welcome comment  # name of the job inside a workflow ("build" is the default if not specified)
    runs-on: ubuntu-latest      # specified runner enviornment (vm or container)

    # define the actions that are performed
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"  # adds comment when pull request is opened
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                     # set the enviornment variable to (created when workflow runs)
          PR_URL: ${{ github.event.pull_request.html_url }}             # set URL environment variable to the URL of newly created pull request (used in gh command)
